services:
    oro_health_check.check.elasticsearch:
        class: Oro\Bundle\HealthCheckBundle\Check\ElasticsearchCheck
        arguments:
            - '@oro_elasticsearch.client.factory'
            - "@=service('oro_search.engine.parameters').getEngineName()"
            - "@=service('oro_elasticsearch.engine.parameters_provider').getEngineParameters()"
        tags:
            - { name: liip_monitor.check, alias: elasticsearch }
