parameters:
    oro_health_check_websocket_frontend_secure_ports: [443]
    oro_health_check_websocket_frontend_secure_protocol: tls
    oro_health_check_websocket_frontend_ssl_context_options: []

services:
    oro_health_check.listener.maintenance:
        class: Oro\Bundle\HealthCheckBundle\EventListener\MaintenanceListener
        decorates: 'oro_maintenance.maintenance_listener'
        arguments:
            - '@oro_health_check.listener.maintenance.inner'
            -
                - 'liip_monitor_health_interface'
                - 'liip_monitor_list_checks'
                - 'liip_monitor_list_all_checks'
                - 'liip_monitor_list_groups'
                - 'liip_monitor_run_all_checks'
                - 'liip_monitor_run_single_check'

    oro_health_check.check.file_storage:
        class: Oro\Bundle\HealthCheckBundle\Check\FileStorageCheckCollection
        arguments:
            - '%kernel.project_dir%'
            -
                fs_var_cache_prod: '%kernel.cache_dir%'
                fs_var_logs: '%kernel.logs_dir%'
                fs_var_data: '%kernel.project_dir%/var/data'
                fs_public_media: '%kernel.project_dir%/public/media'
        tags:
            - { name: liip_monitor.check_collection, alias: file_storage }

    oro_health_check.check.redis:
        class: Oro\Bundle\HealthCheckBundle\Check\RedisCheckCollection
        arguments:
            -
                'Redis cache': '@?snc_redis.cache'
                'Redis doctrine cache': '@?snc_redis.doctrine'
                'Redis session storage': '@?snc_redis.session'
        tags:
            - { name: liip_monitor.check_collection, alias: redis_servers }

    oro_health_check.check.doctrine_dbal:
        class: Oro\Bundle\HealthCheckBundle\Check\DoctrineDBALCheck
        arguments:
            - '@doctrine'
        tags:
            - { name: liip_monitor.check, alias: doctrine_dbal }

    oro_health_check.check.mail_transport:
        class: Oro\Bundle\HealthCheckBundle\Check\MailTransportCheck
        arguments:
            - !abstract '$transportDsn defined in MailTransportCheckPass'
            - '@oro_email.mailer.checker.connection_checkers'
            - '@translator'
        tags:
            - { name: liip_monitor.check, alias: mail_transport }

    oro_health_check.check.rabbitmq:
        class: Oro\Bundle\HealthCheckBundle\Check\RabbitMQCheck
        arguments:
            - '%message_queue_transport_config%'
        tags:
            - { name: liip_monitor.check, alias: rabbitmq_server }

    oro_health_check.websocket_client.frontend:
        class: Oro\Bundle\SyncBundle\Client\WebsocketClient
        public: false
        arguments:
            - '@oro_sync.client.wamp.factory'
            - '@oro_health_check.client_frontend_attributes'
            - '@oro_sync.authentication.ticket_provider'

    oro_health_check.client.connection_checker.frontend:
        class: Oro\Bundle\SyncBundle\Client\ConnectionChecker
        public: false
        arguments:
            - '@oro_health_check.websocket_client.frontend'

    oro_health_check.check.websocket_backend:
        class: Oro\Bundle\HealthCheckBundle\Check\WebSocketCheck
        arguments:
            - '@oro_sync.client.connection_checker'
            - 'backend'
        tags:
            - { name: liip_monitor.check, alias: websocket_backend }

    oro_health_check.check.websocket_frontend:
        class: Oro\Bundle\HealthCheckBundle\Check\WebSocketCheck
        arguments:
            - '@oro_health_check.client.connection_checker.frontend'
            - 'frontend'
            - false
        tags:
            - { name: liip_monitor.check, alias: websocket_frontend }

    oro_health_check.check.maintenance_mode:
        class: Oro\Bundle\HealthCheckBundle\Check\MaintenanceModeCheck
        arguments:
            - '@oro_maintenance.driver.factory'
        tags:
            - { name: liip_monitor.check, alias: maintenance_mode }

    oro_health_check.client_frontend_attributes:
        class: Oro\Bundle\SyncBundle\Client\Wamp\Factory\ClientAttributes
        public: false
        arguments:
            - '%websocket_frontend_host%'
            - '%websocket_frontend_port%'
            - '%websocket_frontend_path%'
            - "@=parameter('websocket_frontend_port') in parameter('oro_health_check_websocket_frontend_secure_ports') ? parameter('oro_health_check_websocket_frontend_secure_protocol') : 'tcp'"
            - '%oro_health_check_websocket_frontend_ssl_context_options%'

    oro_health_check.helper.logger_reporter:
        class: Oro\Bundle\HealthCheckBundle\Helper\LoggerReporter
        arguments:
            - '@logger'
