services:
    oro_health_check.listener.maintenance:
        class: Oro\Bundle\HealthCheckBundle\EventListener\MaintenanceListener
        decorates: 'lexik_maintenance.listener'
        arguments:
            - '@oro_health_check.listener.maintenance.inner'
            -
                - 'liip_monitor_health_interface'
                - 'liip_monitor_list_checks'
                - 'liip_monitor_list_all_checks'
                - 'liip_monitor_list_groups'
                - 'liip_monitor_run_all_checks'
                - 'liip_monitor_run_single_check'

    oro_health_check.check.file_storage:
        class: Oro\Bundle\HealthCheckBundle\Check\FileStorageCheckCollection
        arguments:
            - '%kernel.project_dir%'
            -
                - '%kernel.cache_dir%'
                - '%kernel.logs_dir%'
                - '%kernel.project_dir%/public/media'
                - '%kernel.project_dir%/public/uploads'
                - '%kernel.project_dir%/var/%oro_attachment.attachments_dir%'
                - '%kernel.project_dir%/var/%oro_importexport.importexport_dir%'
        tags:
            - { name: liip_monitor.check_collection, alias: file_storage }

    oro_health_check.check.redis:
        class: Oro\Bundle\HealthCheckBundle\Check\RedisCheckCollection
        arguments:
            - '@service_container'
            -
                'Redis cache': snc_redis.cache
                'Redis doctrine cache': snc_redis.doctrine
                'Redis session storage': snc_redis.session
        tags:
            - { name: liip_monitor.check_collection, alias: redis_servers }

    oro_health_check.check.doctrine_dbal:
        class: Oro\Bundle\HealthCheckBundle\Check\DoctrineDBALCheck
        arguments:
            - '@doctrine'
        tags:
            - { name: liip_monitor.check, alias: doctrine_dbal }

    oro_health_check.check.mail_transport:
        class: Oro\Bundle\HealthCheckBundle\Check\MailTransportCheck
        arguments:
            - '@oro_email.direct_mailer'
        tags:
            - { name: liip_monitor.check, alias: mail_transport }

    oro_health_check.check.rabbitmq:
        class: Oro\Bundle\HealthCheckBundle\Check\RabbitMQCheck
        arguments:
            - '%message_queue_transport_config%'
        tags:
            - { name: liip_monitor.check, alias: rabbitmq_server }

    oro_health_check.websocket_client.frontend:
        class: Oro\Bundle\SyncBundle\Client\WebsocketClient
        public: false
        arguments:
            - '@oro_sync.client.factory.gos'
            - '@oro_sync.authentication.ticket_provider'
            - '%websocket_frontend_host%'
            - '%websocket_frontend_port%'
            - '%websocket_frontend_path%'

    oro_health_check.client.connection_checker.frontend:
        class: Oro\Bundle\SyncBundle\Client\ConnectionChecker
        public: false
        arguments:
            - '@oro_health_check.websocket_client.frontend'

    oro_health_check.check.websocket:
        class: Oro\Bundle\HealthCheckBundle\Check\WebSocketCheck
        arguments:
            - '@oro_sync.client.connection_checker'
            - '@oro_health_check.client.connection_checker.frontend'
        tags:
            - { name: liip_monitor.check, alias: websocket }

    oro_health_check.check.maintenance_mode:
        class: Oro\Bundle\HealthCheckBundle\Check\MaintenanceModeCheck
        arguments:
            - '@lexik_maintenance.driver.factory'
        tags:
            - { name: liip_monitor.check, alias: maintenance_mode }
