liip_monitor:
    enable_controller: true

security:
    firewalls:
        healthcheck_http_status_checks:
            pattern:   /healthcheck/http_status_check(s$|/.*)
            provider:  chain_provider

oro_security:
    access_control:
        - { path: ^%web_backend_prefix%/healthcheck/http_status_check(s$|/.*), roles: PUBLIC_ACCESS }

oro_maintenance:
    authorized:
        route: 'liip_monitor_run_all_checks_http_status'
